project:
  type: website
  render:
    - "*.qmd"
    - "!*.md"
  
website:
  title: Maria Kuruvilla
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: "#projects"
        text: Projects
      - href: "#publications"
        text: Publications
      - href: "#teaching"
        text: Teaching
    tools:
      - icon: github
        href: https://github.com/maria-kuruvilla
      
editor: visual

format:
  html:
    theme:
      - cosmo
      - custom.scss
    date-format: null # This hides dates globally